import type { Country } from "@/types/UserTypes";

export const countries: Country[] = [
  { id: "1", name: "United States" },
  { id: "2", name: "Canada" },
  { id: "3", name: "United Kingdom" },
  { id: "4", name: "Australia" },
  { id: "5", name: "Germany" },
  { id: "6", name: "France" },
  { id: "7", name: "Japan" },
  { id: "8", name: "China" },
  { id: "9", name: "India" },
  { id: "10", name: "Brazil" },
  { id: "11", name: "Mexico" },
  { id: "12", name: "Italy" },
  { id: "13", name: "Spain" },
  { id: "14", name: "Russia" },
  { id: "15", name: "South Korea" },
  { id: "16", name: "Netherlands" },
  { id: "17", name: "Sweden" },
  { id: "18", name: "Norway" },
  { id: "19", name: "Denmark" },
  { id: "20", name: "Finland" },
  { id: "21", name: "Switzerland" },
  { id: "22", name: "Austria" },
  { id: "23", name: "Belgium" },
  { id: "24", name: "Ireland" },
  { id: "25", name: "Portugal" },
  { id: "26", name: "Greece" },
  { id: "27", name: "Turkey" },
  { id: "28", name: "Argentina" },
  { id: "29", name: "Chile" },
  { id: "30", name: "Colombia" },
];
